version: "2"
services:
  webserver:
    image: "mymoodle/boni:latest"
    depends_on:
      - db
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html"
    environment:
      MOODLE_DOCKER_DBTYPE: mysqli
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodleuser
      MOODLE_DOCKER_DBPASS: "yourpassword"
      MOODLE_DOCKER_BROWSER: firefox
      MOODLE_DOCKER_WEB_HOST: localhost
      MOODLE_DOCKER_WEB_PORT: 8002
    ports:
      - "8002:80"
  db:
    image: mysql:5
    command: >
                --character-set-server=utf8mb4
                --collation-server=utf8mb4_bin
                --innodb_file_format=barracuda
                --innodb_file_per_table=On
                --innodb_large_prefix=On
    environment:
      MYSQL_ROOT_PASSWORD: "bonimat"
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: "yourpassword"
